### ISSUE TITLE
running the certmonger_certificate more than once always resubmits

### ISSUE THREAD

**Issue by JAORMX** [earsdown/puppet-certmonger#11]
It seems that we are doing always resubmission of the certificate. This is because we are checking wronly the force_resubmit.

**Comment by JAORMX** [comment]
Addressed by #12 ... still gotta test it though.

**Comment by JAORMX** [comment]
Tried #12 and it works for me.

**Comment by earsdown** [comment]
Nice work, I'm still using the verify shell script so I didn't get hit with this bug.
