### ISSUE TITLE
Migrating to voxpupuli

### ISSUE THREAD

**Issue by earsdown** [earsdown/puppet-certmonger#14]
Any objections to transferring this module to voxpupuli?

@JAORMX

**Comment by JAORMX** [comment]
no objections

**Comment by JAORMX** [comment]
Actually it seems to me that it's a good idea.

**Comment by JAORMX** [comment]
@earsdown is there anything needed from my side to help with this?

**Comment by earsdown** [comment]
@JAORMX 

The process is documented here: https://voxpupuli.org/docs/#migrating-a-module-to-voxpupuli

I've also been asked to remove puppet<4 support, which is fine for me. Are you okay with this as well?

So, if you have time, maybe remove puppet<4 support, refresh modulesync, and do whatever else you can see needs to be done, without affecting users?

**Comment by JAORMX** [comment]
@earsdown what do you mean by removing puppet < 4 support? Removing it from CI?

**Comment by vinzent** [comment]
@earsdown what is your motivation to move this to voxpupuli? Will you stop working on this or will you still be contributing to it?

**Comment by vinzent** [comment]
@JAORMX VoxPupuli modules are going to be >= Puppet4 only . see https://voxpupuli.org/blog/2016/12/22/putting-down-puppet-3/

**Comment by EmilienM** [comment]
@vinzent as a puppet-certmonger user, I don't see any blocker. We use the module in OpenStack with Puppet 4 and it runs perfectly well.

**Comment by vinzent** [comment]
@EmilienM Just want to know the motivation. I really like seeing moving modules to VP. Just hope it is not a "over the fence" action and that we can have new members onboarding. :)

**Comment by JAORMX** [comment]
@vinzent at least I'll keep working on it. @earsdown will you?

**Comment by alexjfisher** [comment]
Worried about having to fix a ton of rubocop violations?
Ta-dah! https://github.com/earsdown/puppet-certmonger/pull/15

**Comment by JAORMX** [comment]
@alexjfisher thanks for the commit! #15 has merged

**Comment by JAORMX** [comment]
@vinzent : Right now both @earsdown and me can merge patches in this repository. when migrating this repo to voxpupuli, will we still be able to do that?

**Comment by earsdown** [comment]
@JAORMX @EmilienM @alexjfisher @vinzent - now that puppet has announced its partner program, my employer has "suddenly" decided they're interested in contributing resources towards on-going maintenance of this module after all - and they'd prefer I didn't transfer it :disappointed: 

Btw, is anyone using the change-perms-restart script?

**Comment by JAORMX** [comment]
@earsdown we're not. all we're using is the init.pp manifest and the puppet provider/type for certificates.

**Comment by earsdown** [comment]
Closing due to deprecation in favour of https://github.com/saltedsignal/puppet-certmonger
