### ISSUE TITLE
Add ability to specify additional EKUs on certificate request

### ISSUE THREAD

**Issue by dantrainor** [earsdown/puppet-certmonger#16]
RFC5280 says that a certificate may have additional Extended Key Usage attributes.  Implementing this native ability within puppet-certmonger would be ideal.  The only option we have right now is to bake a refresh of the cert with additional EKUs via -U option in postsavecmd, similar to:

/bin/local-getcert resubmit -i "$REQUEST_NICKNAME" -w -v -U id-kp-clientAuth  -U id-kp-serverAuth

**Comment by JAORMX** [comment]
This shouldn't be too hard to implement; but I would like to get #14 figured out first before starting to work on this.

**Comment by earsdown** [comment]
@dantrainor not sure if you're using the defined type or the native type/provider... if you're using the defined type then support for EKU and Key Usage attributes was added in PR #17 ... could you test?

**Comment by JAORMX** [comment]
@earsdown he's using the type/provider.

**Comment by earsdown** [comment]
Closing due to deprecation in favour of https://github.com/saltedsignal/puppet-certmonger
