### ISSUE TITLE
Certificate profile property for custom type/provider

### ISSUE THREAD

**Issue by earsdown** [earsdown/puppet-certmonger#5]
Certmonger has the ability to ask the CA to process the request using the named profile or template (i.e. the `-T PROFILE` option). It would be great if the custom type/provider had support for this as well. I'd like to refactor the `certmonger::request_ipa_cert` defined type so that it uses the custom type/provider (i.e. instead of the execs), and I can't do that yet due to the lack of certificate profile support.

**Comment by JAORMX** [comment]
This should be addressed by https://github.com/earsdown/puppet-certmonger/pull/6

**Comment by earsdown** [comment]
Is it worth updating the unit tests for this as well?

**Comment by JAORMX** [comment]
That's probably a good idea. I can do that on monday. Gotta go for today :/

**Comment by JAORMX** [comment]
Alright, #6 should now fix the issue and add unit tests.

**Comment by JAORMX** [comment]
Is it ok to merge it?

**Comment by earsdown** [comment]
Looks good to me. I'll try to find some time over the next few days/weeks to play with the new type/provider. Do you want this on the forge straight away or happy to wait?

**Comment by JAORMX** [comment]
No problem, I can wait.

**Comment by earsdown** [comment]
Cool, thanks again for everything @JAORMX
